#!/bin/bash

# Link dotfiles to home directory

# Locate dotfiles dir
var1=$(tree -i -fd "${HOME}" | grep "dotfiles")

mkdir -p ~/.config
mkdir -p ~/.config/alacritty/themes
mkdir -p ~/.config/tmux/plugins/tmux-dotbar
mkdir -p ~/.vim/autoload

ln -sf "${var1}"/.bashrc ~/.bashrc
ln -sf "${var1}"/.vimrc ~/.vimrc
ln -sf "${var1}"/.vim/autoload/plug.vim ~/.vim/autoload/plug.vim
ln -sf "${var1}"/.tmux.conf ~/.tmux.conf
ln -sf ~/Documents/dotfiles/.config/tmux/plugins/tmux-dotbar/dotbar.tmux ~/.config/tmux/plugins/tmux-dotbar/dotbar.tmux
ln -sf "${var1}"/.config/alacritty/alacritty.toml ~/.config/alacritty/alacritty.toml 
ln -sf "${var1}"/.config/alacritty/themes/tokyo-night-storm.toml ~/.config/alacritty/themes/tokyo-night-storm.toml
echo "Dotfiles linked!"
