#!/bin/bash

# Link dotfiles to home directory

mkdir -p ~/.config
mkdir -p ~/.config/alacritty/themes

ln -sf ~/Documents/dotfiles/.bashrc ~/.bashrc
ln -sf ~/Documents/dotfiles/.vimrc ~/.vimrc
ln -sf ~/Documents/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/Documents/dotfiles/.config/alacritty/alacritty.toml ~/.config/alacritty/alacritty.toml 
ln -sf ~/Documents/dotfiles/.config/alacritty/themes/tokyo-night-storm.toml ~/.config/alacritty/themes/tokyo-night-storm.toml
echo "Dotfiles linked!"
